workspace:
  base: /go
  path: src/github.com/josmo/drone-ecs
pipeline:
  build:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  publish:
    image: plugins/docker
    username: josmo
    password: ${DOCKER_PASSWORD}
    secrets: [ docker_password ]
    repo: peloton/drone-ecs
    tag:
      - latest
      - ${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push

plugin:
  name: ECS
  desc: Deploy or update a project on AWS ECS
  type: deploy
  image: peloton/drone-ecs
  labels:
    - aws
    - paas
