workspace:
  base: /go
pipeline:
  build:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  publish:
    coverage:
      when:
        branch: master
    docker:
      image: plugins/docker
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASS}
      email: ${DOCKER_EMAIL}
      repo: plugins/drone-ecs
      tag: latest
      when:
        branch: master

plugin:
  name: ECS
  desc: Deploy or update a project on AWS ECS
  type: deploy
  image: plugins/drone-ecs
  labels:
    - aws
    - paas
